# Site settings
title: "Daksh Patel Resume"
description: "A resume template for Daksh Patel."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Daksh A. Patel"
resume_title:                   "Electrical Engineer In Training"
resume_contact_email:           "dakshpatel147@gmail.com"
resume_contact_telephone:       "226-929-0800"
resume_contact_address:         "245 Summerside Pl, Port Elgin"
resume_header_contact_info: "245 Summerside Pl, Port Elgin | 226-929-0800 | dakshpatel147@gmail.com"
resume_header_intro: "<p>A dynamic, passionate, resourceful and multitalented electrical engineering student having an extensive exposure to methods engineering, project management, and the restructuring and redefining of electrical operations. Creative problem solver who has consistently completed projects on time and within budget. Outstanding interpersonal and communication skills with the ability to blend and smoothly interact with clients, contractors and/or co-workers of various cultural backgrounds, therefore, establishing a top-notch coordination and execution of projects in a very saturated market.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/GurenMarkV/GurenMarkV.github.io"
  resume_twitter_url:           "http://twitter.com/GurenMarkV"
# resume_dribbble_url:          "https://dribbble.com/jag"
# resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dakshpatel147"
  resume_instagram_url:         "https://www.instagram.com/gurenmarkv"
  resume_website_url:           "http://dakshpatel.me"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
